# Generated by Django 5.1.6 on 2025-02-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_image_course_level_alter_course_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='full_description',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание (Markdown)'),
        ),
    ]
