# Generated by Django 5.1.6 on 2025-02-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='HeroBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.TextField(verbose_name='Описание')),
                ('btn_to_action', models.CharField(max_length=255, verbose_name='Призыв к действию')),
                ('hero_image', models.ImageField(blank=True, upload_to='main_page/', verbose_name='Главное изображение')),
            ],
            options={
                'verbose_name': 'Hero - секция',
                'verbose_name_plural': 'Hero - секция',
            },
        ),
        migrations.CreateModel(
            name='JoinOurCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_block', models.CharField(max_length=255, verbose_name='Заголовок блока')),
                ('subtitle_block', models.TextField(verbose_name='Описание блока')),
            ],
            options={
                'verbose_name': 'Название блока подписки',
                'verbose_name_plural': 'Описание блока подписки',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_benefit', models.CharField(max_length=255, verbose_name='Заголовок приемущества')),
                ('description_benefit', models.CharField(max_length=255, verbose_name='Описание приемущества')),
                ('benefit_image', models.ImageField(blank=True, upload_to='main_page/', verbose_name='Изображение приемущества')),
            ],
            options={
                'verbose_name': 'Блок подписки',
                'verbose_name_plural': 'Блоки подписки',
            },
        ),
    ]
