# Generated by Django 5.1.6 on 2025-02-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionbenefit',
            name='benefit_image',
        ),
        migrations.AddField(
            model_name='subscriptionbenefit',
            name='benefit_svg',
            field=models.FileField(blank=True, help_text='Загрузите SVG файл. Только формат .svg разрешен.', upload_to='main_page/svg/', verbose_name='SVG файл преимущества'),
        ),
        migrations.AlterField(
            model_name='subscriptionbenefit',
            name='description_benefit',
            field=models.CharField(max_length=255, verbose_name='Описание преимущества'),
        ),
        migrations.AlterField(
            model_name='subscriptionbenefit',
            name='title_benefit',
            field=models.CharField(max_length=255, verbose_name='Заголовок преимущества'),
        ),
    ]
