# Generated by Django 5.1.6 on 2025-03-04 11:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_full_description'),
        ('mainPage', '0002_remove_subscriptionbenefit_benefit_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email подписчика')),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата подписки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная подписка')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждена')),
                ('confirmation_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='Токен подтверждения')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.category', verbose_name='Предпочитаемая категория')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
